I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter1/meeting.rpy", line 403, in script
    Kyle "Мадам Дюморье, $%@#! Прямо у меня под носом, эта хитрая змея."
ValueError: unsupported format character '@' (0x40) at index 17

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter1/meeting.rpy", line 403, in script
    Kyle "Мадам Дюморье, $%@#! Прямо у меня под носом, эта хитрая змея."
  File "/Users/apogodaeva/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/apogodaeva/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/apogodaeva/Documents/renpy-8.3.4-sdk/renpy/exports/sayexports.py", line 121, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character '@' (0x40) at index 17

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.6.25022803
CIRCUS 1.0
Thu Jun 26 13:01:09 2025
