I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/free_time.rpy", line 214, in script
    Missis "Здравствуй, [name]"
Exception: Sayer 'Missis' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/free_time.rpy", line 214, in script
    Missis "Здравствуй, [name]"
  File "/Users/apogodaeva/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/apogodaeva/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/apogodaeva/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Missis' is not defined.

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.6.25022803
CIRCUS 1.0
Mon Mar 17 17:28:11 2025
